---
- name: Setup Raspberry Pi mit Webserver, Tailscale, Firewall, Backend und WLAN-Failover
  hosts: all
  become: yes
  connection: local

  vars:
    github_repo: "https://github.com/enderahd/Feuerwehr_Dashboard.git"
    target_dir: "/home/{{ ansible_user_id }}/Feuerwehr_Dashboard"
    backend_entry: "API_backend.py"
    backend_port: 5000
    tailscale_auth_key: ""  # Optional: hier deinen Tailscale-Key eintragen
    html_target_dir: "/var/www/html"
    log_file: "/home/{{ ansible_user_id }}/ansible_setup.log"
    fallback_ssid: "fallback"
    fallback_password: "FFW2025"
    fallback_interface: "wlan0"

  tasks:

  - name: Logging vorbereiten
    lineinfile:
      path: "{{ log_file }}"
      line: "----- Playbook gestartet: {{ ansible_date_time.iso8601 }} -----"
      create: yes
      owner: "{{ ansible_user_id }}"
      group: "{{ ansible_user_id }}"
      mode: '0644'

  - name: Paketquellen aktualisieren
    apt:
      update_cache: yes

  - name: Notwendige Pakete installieren
    apt:
      name:
        - nginx
        - git
        - ufw
        - curl
        - python3
        - python3-venv
        - python3-pip
        - dnsmasq
        - hostapd
        - wireless-tools
        - iproute2
      state: present

  - name: Tailscale installieren
    shell: curl -fsSL https://tailscale.com/install.sh | sh
    args:
      creates: /usr/sbin/tailscaled

  - name: Tailscale trennen (wenn vorhanden)
    shell: tailscale logout
    ignore_errors: true

  - name: Tailscale starten (wenn Key vorhanden)
    shell: tailscale up --auth-key={{ tailscale_auth_key }}
    when: tailscale_auth_key != ""

  - name: Lokale IP-Adresse neu ermitteln
    shell: hostname -I | awk '{print $1}'
    register: local_ip_raw

  - name: Setze lokale IP
    set_fact:
      local_ip: "{{ local_ip_raw.stdout.strip() }}"

  - name: Berechne lokales Subnetz (z. B. 192.168.1.0/24)
    set_fact:
      local_subnet: "{{ local_ip | regex_replace('(\\d+\\.\\d+\\.\\d+)\\.\\d+', '\\1.0/24') }}"

  - name: Tailscale-IP ermitteln
    shell: tailscale ip -4
    register: tailscale_ip_raw
    failed_when: false
    changed_when: false

  - name: Setze Tailscale-IP (wenn vorhanden)
    set_fact:
      tailscale_ip: "{{ tailscale_ip_raw.stdout | default('') | trim }}"
    when: tailscale_ip_raw is defined and 'stdout' in tailscale_ip_raw

  - name: Schreibe Tailscale-IP ins Log (wenn vorhanden)
    lineinfile:
      path: "{{ log_file }}"
      line: "Tailscale IP: {{ tailscale_ip }}"
    when: tailscale_ip is defined and tailscale_ip != ""

  - name: Teste Internetverbindung
    shell: ping -c 1 1.1.1.1
    register: ping_test
    ignore_errors: true

  - name: Konfiguriere WLAN-Fallback (wenn kein Internet)
    block:
      - name: Schreibe hostapd.conf
        copy:
          dest: /etc/hostapd/hostapd.conf
          content: |
            interface={{ fallback_interface }}
            driver=nl80211
            ssid={{ fallback_ssid }}
            hw_mode=g
            channel=7
            wmm_enabled=0
            macaddr_acl=0
            auth_algs=1
            ignore_broadcast_ssid=0
            wpa=2
            wpa_passphrase={{ fallback_password }}
            wpa_key_mgmt=WPA-PSK
            wpa_pairwise=TKIP
            rsn_pairwise=CCMP

      - name: Setze hostapd Konfiguration
        lineinfile:
          path: /etc/default/hostapd
          regexp: '^#?DAEMON_CONF='
          line: 'DAEMON_CONF="/etc/hostapd/hostapd.conf"'

      - name: Schreibe dnsmasq.conf
        copy:
          dest: /etc/dnsmasq.conf
          content: |
            interface={{ fallback_interface }}
            dhcp-range=192.168.50.10,192.168.50.50,255.255.255.0,24h

      - name: Setze statische IP auf WLAN Interface
        lineinfile:
          path: /etc/dhcpcd.conf
          line: |
            interface {{ fallback_interface }}
            static ip_address=192.168.50.1/24

      - name: Aktiviere WLAN Dienste
        systemd:
          name: "{{ item }}"
          enabled: yes
          state: started
        loop:
          - hostapd
          - dnsmasq

    when: ping_test.failed

  - name: Alte UFW-Regeln zurücksetzen
    shell: ufw --force reset
    notify: reload firewall

  - name: Firewall aktivieren
    ufw:
      state: enabled
      policy: deny

  - name: Erlaube alle Verbindungen über WLAN (Fallback-Modus)
    ufw:
      rule: allow
      interface: "{{ fallback_interface }}"

  - name: Erlaube SSH über Tailscale
    ufw:
      rule: allow
      from_ip: "{{ tailscale_ip }}"
      port: 22
      proto: tcp
    when: tailscale_ip is defined and tailscale_ip != ""

  - name: Erlaube Backend-Port über Tailscale
    ufw:
      rule: allow
      from_ip: "{{ tailscale_ip }}"
      port: "{{ backend_port }}"
      proto: tcp
    when: tailscale_ip is defined and tailscale_ip != ""

  - name: Erlaube Backend-Port über lokale IP
    ufw:
      rule: allow
      from_ip: "{{ local_ip }}"
      port: "{{ backend_port }}"
      proto: tcp

  - name: Erlaube HTTP über lokales Subnetz
    ufw:
      rule: allow
      from_ip: "{{ local_subnet }}"
      port: 80
      proto: tcp

  - name: Erlaube HTTPS über lokales Subnetz
    ufw:
      rule: allow
      from_ip: "{{ local_subnet }}"
      port: 443
      proto: tcp

  - name: Schreibe IPs ins Log
    lineinfile:
      path: "{{ log_file }}"
      line: "Lokale IP: {{ local_ip }}, Subnetz: {{ local_subnet }}"

  - name: Lösche altes Projektverzeichnis (falls vorhanden)
    file:
      path: "{{ target_dir }}"
      state: absent

  - name: Erstelle Zielordner neu
    file:
      path: "{{ target_dir }}"
      state: directory
      owner: "{{ ansible_user_id }}"
      group: "{{ ansible_user_id }}"
      mode: '0755'

  - name: GitHub-Repo klonen
    git:
      repo: "{{ github_repo }}"
      dest: "{{ target_dir }}"
      version: "main"
      force: yes

  - name: Setze Dateirechte auf Benutzer
    file:
      path: "{{ target_dir }}"
      owner: "{{ ansible_user_id }}"
      group: "{{ ansible_user_id }}"
      recurse: yes

  - name: Erstelle virtuelle Umgebung
    shell: python3 -m venv {{ target_dir }}/venv
    args:
      creates: "{{ target_dir }}/venv/bin/python"

  - name: Installiere Abhängigkeiten aus requirements.txt
    pip:
      requirements: "{{ target_dir }}/requirements.txt"
      virtualenv: "{{ target_dir }}/venv"
      virtualenv_python: python3

  - name: Systemd-Service für Backend erstellen
    copy:
      dest: /etc/systemd/system/backend.service
      content: |
        [Unit]
        Description=Python-Backend (venv)
        After=network.target

        [Service]
        User={{ ansible_user_id }}
        WorkingDirectory={{ target_dir }}
        ExecStart={{ target_dir }}/venv/bin/python {{ target_dir }}/{{ backend_entry }}
        Restart=always

        [Install]
        WantedBy=multi-user.target

  - name: systemd neu laden
    systemd:
      daemon_reload: yes

  - name: Backend-Service aktivieren und starten
    systemd:
      name: backend.service
      enabled: yes
      state: started

  - name: Lösche Standard-Nginx-Datei, falls vorhanden
    file:
      path: /var/www/html/index.nginx-debian.html
      state: absent

  - name: Kopiere Website-Dateien nach /var/www/html
    shell: |
      mkdir -p {{ html_target_dir }}
      cp -r {{ target_dir }}/images {{ html_target_dir }}/
      cp -r {{ target_dir }}/output {{ html_target_dir }}/
      cp -r {{ target_dir }}/pdfs {{ html_target_dir }}/
      cp {{ target_dir }}/styles.css {{ html_target_dir }}/
      cp {{ target_dir }}/script.js {{ html_target_dir }}/
      cp {{ target_dir }}/index.html {{ html_target_dir }}/
      chown -R www-data:www-data {{ html_target_dir }}
      chmod -R 755 {{ html_target_dir }}
    notify: restart nginx

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted

    - name: reload firewall
      shell: ufw reload
